Repository webpack/enhanced-resolve, pull requests merged in 2018-06, with the labels that each got.

#150 Fixes for Windows when using symbolic links
  lib/SymlinkPlugin.js
  lib/getPaths.js
  test/symlink.js
Labels: PR: CI-ok, PR: reviewed-approved

#148 Update the plugin boilerplate in README
  README.md
Labels: PR: CI-ok

#144 Add more info in the deprecation warnings
  lib/Resolver.js
  lib/createInnerCallback.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#155 fix aliasing of absolute paths
  lib/AliasPlugin.js
  test/alias.js
Labels: PR: CI-ok, PR: unreviewed

#156 Don't crash when main = "./"
  lib/MainFieldPlugin.js
  test/fixtures/main-field-self/index.js
  test/fixtures/main-field-self/package.json
  test/resolve.js
Labels: PR: CI-ok, PR: unreviewed
