Repository webpack/enhanced-resolve, pull requests merged in 2019-07, with the labels that each got.

#182 Improvements for new major version
  .eslintrc.js
  .gitignore
  .travis.yml
  README.md
  lib/AliasFieldPlugin.js
  lib/AliasPlugin.js
  lib/AppendPlugin.js
  lib/CloneBasenamePlugin.js
  lib/DescriptionFilePlugin.js
  lib/DescriptionFileUtils.js
  lib/DirectoryExistsPlugin.js
  lib/FileExistsPlugin.js
  lib/FileKindPlugin.js
  lib/JoinRequestPartPlugin.js
  lib/JoinRequestPlugin.js
  lib/MainFieldPlugin.js
  lib/ModuleAppendPlugin.js
  lib/ModuleKindPlugin.js
  lib/ModulesInHierachicDirectoriesPlugin.js
  lib/ModulesInRootPlugin.js
  lib/NodeJsInputFileSystem.js
  lib/ParsePlugin.js
  lib/PnpPlugin.js
  lib/Resolver.js
  lib/ResolverFactory.js
  lib/ResultPlugin.js
  lib/SymlinkPlugin.js
  lib/SyncAsyncFileSystemDecorator.js
  lib/UseFilePlugin.js
  lib/createInnerContext.js
  lib/forEachBail.js
  lib/globToRegExp.js
  lib/node.js
  lib/pathUtils.js
  package.json
  test/alias.js
  test/browserField.js
  test/dependencies.js
  test/extensions.js
  test/fixtures/extensions/node_modules/module.js
  test/fixtures/extensions/node_modules/module/index.ts
  test/fixtures/node_modules/m2-loader/b.js
  test/fixtures/pnp/pkg/dir/index.js
  test/fixtures/pnp/pkg/index.js
  test/fixtures/pnp/pkg/main.js
  test/fixtures/pnp/pkg/package-alias/browser.js
  test/fixtures/pnp/pkg/package-alias/index.js
  test/fixtures/pnp/pkg/package.json
  test/fixtures/pnp/pkg/typescript/index.ts
  test/forEachBail.js
  test/missing.js
  test/pnp.js
  test/resolve.js
  test/unsafe-cache.js
  yarn.lock
Labels: PR: CI-ok, PR: unreviewed

#183 Readme and bugfix
  README.md
  lib/MainFieldPlugin.js
  test/fixtures/main-field-self2/index.js
  test/fixtures/main-field-self2/package.json
  test/resolve.js
Labels: PR: CI-ok, PR: unreviewed

#185 gitignore .idea .vscode .DS_Store
  .gitignore
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#187 add support for "false" alias
  lib/AliasPlugin.js
  lib/ResolverFactory.js
  test/alias.js
Labels: PR: CI-ok, PR: unreviewed

#189 update tapable to get rid of withName
  lib/Resolver.js
  package.json
  yarn.lock
Labels: PR: CI-ok, PR: unreviewed

#186 Linting with typescript
  lib/Resolver.js
  lib/ResolverFactory.js
  lib/SyncAsyncFileSystemDecorator.js
  lib/forEachBail.js
  package.json
  test/forEachBail.js
  test/missing.js
  tsconfig.json
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#188 enforce eslint require-hyphen-before-param-description
  .eslintrc.js
  package.json
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved
