Repository webpack/enhanced-resolve, pull requests merged in 2020-03, with the labels that each got.

#204 make trailing slash module path resolve correctly
  lib/FileKindPlugin.js
  lib/ResolverFactory.js
  test/extensions.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#208 Big update
  .eslintrc.js
  lib/AliasFieldPlugin.js
  lib/AliasPlugin.js
  lib/AppendPlugin.js
  lib/CachedInputFileSystem.js
  lib/CloneBasenamePlugin.js
  lib/DescriptionFilePlugin.js
  lib/DescriptionFileUtils.js
  lib/DirectoryExistsPlugin.js
  lib/FileExistsPlugin.js
  lib/FileKindPlugin.js
  lib/JoinRequestPartPlugin.js
  lib/JoinRequestPlugin.js
  lib/LogInfoPlugin.js
  lib/MainFieldPlugin.js
  lib/ModuleKindPlugin.js
  lib/ModulesInHierachicDirectoriesPlugin.js
  lib/ModulesInRootPlugin.js
  lib/NextPlugin.js
  lib/ParsePlugin.js
  lib/PnpPlugin.js
  lib/Resolver.js
  lib/ResolverFactory.js
  lib/ResultPlugin.js
  lib/SymlinkPlugin.js
  lib/SyncAsyncFileSystemDecorator.js
  lib/TryNextPlugin.js
  lib/UnsafeCachePlugin.js
  lib/UseFilePlugin.js
  lib/createInnerContext.js
  lib/forEachBail.js
  lib/getInnerRequest.js
  lib/getPaths.js
  lib/node.js
  package.json
  test/extensions.js
  test/plugins.js
  test/pnp.js
  test/symlink.js
  tooling/format-file-header.js
  tsconfig.json
  yarn.lock
Labels: PR: CI-ok, PR: unreviewed

#192 esdoc resolve context
  lib/Resolver.js
Labels: PR: CI-ok, PR: unreviewed

#190 esdoc ResolverFactory, enable strictNullChecks in tsconfig
  lib/AliasFieldPlugin.js
  lib/AliasPlugin.js
  lib/AppendPlugin.js
  lib/CachedInputFileSystem.js
  lib/DescriptionFilePlugin.js
  lib/DirectoryExistsPlugin.js
  lib/FileExistsPlugin.js
  lib/FileKindPlugin.js
  lib/JoinRequestPartPlugin.js
  lib/JoinRequestPlugin.js
  lib/MainFieldPlugin.js
  lib/ModuleKindPlugin.js
  lib/ModulesInHierachicDirectoriesPlugin.js
  lib/ModulesInRootPlugin.js
  lib/NextPlugin.js
  lib/ParsePlugin.js
  lib/PnpPlugin.js
  lib/Resolver.js
  lib/ResolverFactory.js
  lib/ResultPlugin.js
  lib/SymlinkPlugin.js
  lib/TryNextPlugin.js
  lib/UnsafeCachePlugin.js
  lib/UseFilePlugin.js
  test/pnp.js
  test/symlink.js
  tsconfig.json
Labels: PR: conflict, PR: review-outdated

#206 chore: ignore package-lock.json
  .gitignore
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
