Repository webpack/enhanced-resolve, pull requests merged in 2020-09, with the labels that each got.

#237 add imports field support
  lib/ExportsFieldPlugin.js
  lib/ImportsFieldPlugin.js
  lib/Resolver.js
  lib/ResolverFactory.js
  lib/SymlinkPlugin.js
  lib/processExportsField.js
  lib/util/entrypoints.js
  lib/util/identifier.js
  lib/util/path.js
  test/exportsField.js
  test/fixtures/imports-field/a.js
  test/fixtures/imports-field/b.js
  test/fixtures/imports-field/node_modules/a/lib/browser.js
  test/fixtures/imports-field/node_modules/a/lib/index.js
  test/fixtures/imports-field/node_modules/a/lib/lib2/main.js
  test/fixtures/imports-field/node_modules/a/lib/main.js
  test/fixtures/imports-field/node_modules/a/main.js
  test/fixtures/imports-field/node_modules/a/package.json
  test/fixtures/imports-field/node_modules/a/x.js
  test/fixtures/imports-field/node_modules/c/index.js
  test/fixtures/imports-field/package.json
  test/identifier.js
  test/importsField.js
  types.d.ts
Labels: PR: CI-ok, PR: reviewed-approved

#241 add fallback option
  lib/ResolverFactory.js
  test/fallback.js
  types.d.ts
Labels: PR: CI-ok, PR: unreviewed

#244 revert #folder handling
  lib/util/identifier.js
  test/identifier.js
Labels: PR: CI-ok, PR: small, PR: unreviewed

#245 resolve PnP at the location of node_modules in the modules option
  lib/PnpPlugin.js
  lib/ResolverFactory.js
  test/fixtures/pnp-a/m2/a.js
  test/pnp.js
Labels: PR: CI-ok, PR: unreviewed

#246 update dependencies
  .prettierignore
  .prettierrc.js
  lib/CachedInputFileSystem.js
  lib/ResolverFactory.js
  lib/SyncAsyncFileSystemDecorator.js
  lib/index.js
  package.json
  test/CachedInputFileSystem.js
  test/alias.js
  test/browserField.js
  test/dependencies.js
  test/extensions.js
  test/fallback.js
  test/fullSpecified.js
  test/incorrect-description-file.js
  test/missing.js
  test/plugins.js
  test/pr-53.js
  test/resolve.js
  test/simple.js
  test/symlink.js
  test/unsafe-cache.js
  types.d.ts
  yarn.lock
Labels: PR: CI-ok, PR: unreviewed

#252 avoid stack overflow due to cached resolving
  lib/CachedInputFileSystem.js
  test/CachedInputFileSystem.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#253 add preferRelative option
  README.md
  lib/ResolverFactory.js
  test/resolve.js
  types.d.ts
Labels: PR: CI-ok, PR: reviewed-approved

#254 feat: `lstat` and `lstatSync`
  lib/CachedInputFileSystem.js
  lib/Resolver.js
  lib/SyncAsyncFileSystemDecorator.js
  test/CachedInputFileSystem.js
  types.d.ts
Labels: PR: CI-ok, PR: unreviewed

#255 resolve folders which look like a fragment
  README.md
  lib/ParsePlugin.js
  lib/Resolver.js
  lib/util/identifier.js
  test/fixtures/no#fragment/#/#.js
  test/fixtures/no.js
  test/resolve.js
Labels: PR: CI-ok, PR: unreviewed
