Repository webpack/enhanced-resolve, pull requests merged in 2020-07, with the labels that each got.

#227 add roots option
  README.md
  lib/ResolverFactory.js
  lib/RootsPlugin.js
  lib/index.js
  test/roots.js
  types.d.ts
Labels: PR: CI-ok, PR: unreviewed

#228 add roots option
  lib/ResolverFactory.js
  lib/RootPlugin.js
  test/roots.js
Labels: PR: CI-ok, PR: non-master, PR: reviewed-approved

#230 refactor CachedFileSystem
  declarations.d.ts
  lib/CachedInputFileSystem.js
  lib/Resolver.js
  test/CachedInputFileSystem.js
  test/pr-53.js
  tsconfig.json
  types.d.ts
Labels: PR: CI-ok, PR: unreviewed

#232 allow to flag requests as already fully specified
  README.md
  lib/AliasFieldPlugin.js
  lib/AliasPlugin.js
  lib/ConditionalPlugin.js
  lib/FileKindPlugin.js
  lib/JoinRequestPartPlugin.js
  lib/ModuleKindPlugin.js
  lib/ParsePlugin.js
  lib/Resolver.js
  lib/ResolverFactory.js
  test/fullSpecified.js
  types.d.ts
Labels: PR: reviewed-approved

#234 fix resolveToContext with fullySpecified
  lib/ResolverFactory.js
  test/fullSpecified.js
Labels: PR: CI-ok, PR: unreviewed

#236 refactor forEachBail.js
  lib/forEachBail.js
Labels: PR: CI-ok, PR: reviewed-approved
