Repository webpack/enhanced-resolve, pull requests merged in 2022-02, with the labels that each got.

#326 add yield in resolve context
  lib/Resolver.js
  lib/ResultPlugin.js
  lib/createInnerContext.js
  lib/getPaths.js
  test/getPaths.js
  test/yield.js
  types.d.ts
Labels: PR: reviewed-approved

#314 chore: add node v16 and node v17 in CI
  .github/workflows/test.yml
Labels: PR: reviewed-approved, PR: small

#321 ci: use setup-node cache for Yarn
  .github/workflows/test.yml
Labels: PR: unreviewed, PR: small

#323 chore: upgrade to Husky 6
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: PR: unreviewed

#320 chore: add cSpell for spell checking
  .cspell.json
  lib/ModulesInHierachicDirectoriesPlugin.js
  lib/ModulesInHierarchicalDirectoriesPlugin.js
  lib/ResolverFactory.js
  lib/SymlinkPlugin.js
  lib/getPaths.js
  package.json
  test/getPaths.js
  test/resolve.js
  tooling/format-file-header.js
  types.d.ts
  yarn.lock
Labels: PR: unreviewed

#331 fix yield
  lib/AliasFieldPlugin.js
  lib/AliasPlugin.js
  lib/Resolver.js
  lib/UnsafeCachePlugin.js
  test/fixtures/yield/a/foo-2/b
  test/fixtures/yield/a/foo-2/c
  test/fixtures/yield/a/foo/a
  test/fixtures/yield/a/foo/b
  test/fixtures/yield/b/foo/a
  test/fixtures/yield/c/foo/a
  test/fixtures/yield/c/foo/package.json
  test/yield.js
Labels: PR: reviewed-approved
