Repository webpack/enhanced-resolve, pull requests merged in 2023-05, with the labels that each got.

#378 chore: update `checkout`, `setup-node`, and `codecov` github actions
  .github/workflows/test.yml
Labels: PR: reviewed-approved, PR: small

#380 fix: resolve for exports fields and exports fields
  lib/ExtensionAliasPlugin.js
  lib/forEachBail.js
  test/exportsField.js
  test/fixtures/exports-field-and-extension-alias/node_modules/@org/pkg/dist/string.js
  test/fixtures/exports-field-and-extension-alias/node_modules/@org/pkg/dist/string.test.d.ts
  test/fixtures/exports-field-and-extension-alias/node_modules/@org/pkg/package.json
  test/fixtures/exports-field-and-extension-alias/node_modules/pkg/dist/string.js
  test/fixtures/exports-field-and-extension-alias/node_modules/pkg/dist/string.test.d.ts
  test/fixtures/exports-field-and-extension-alias/node_modules/pkg/package.json
Labels: PR: reviewed-approved

#336 chore: replace deprecated String.prototype.substr()
  lib/AliasPlugin.js
  lib/DescriptionFilePlugin.js
  lib/DescriptionFileUtils.js
  lib/Resolver.js
  lib/ResolverFactory.js
  lib/getPaths.js
  tooling/format-file-header.js
Labels: PR: reviewed-approved

#379 feat: migrate to jest
  .eslintrc.js
  .github/workflows/test.yml
  .husky/pre-commit
  jest.config.js
  package.json
  test/CachedInputFileSystem.test.js
  test/SyncAsyncFileSystemDecorator.test.js
  test/__snapshots__/alias.test.js.snap
  test/__snapshots__/exportsField.test.js.snap
  test/__snapshots__/fallback.test.js.snap
  test/__snapshots__/importsField.test.js.snap
  test/__snapshots__/restrictions.test.js.snap
  test/alias.js
  test/alias.test.js
  test/browserField.js
  test/browserField.test.js
  test/dependencies.test.js
  test/exportsField.test.js
  test/extension-alias.test.js
  test/extensions.test.js
  test/fallback.js
  test/fallback.test.js
  test/forEachBail.test.js
  test/fullSpecified.test.js
  test/getPaths.test.js
  test/identifier.test.js
  test/importsField.test.js
  test/incorrect-description-file.test.js
  test/missing.test.js
  test/path.test.js
  test/plugins.test.js
  test/pnp.test.js
  test/pr-53.test.js
  test/resolve.test.js
  test/restrictions.js
  test/restrictions.test.js
  test/roots.test.js
  test/scoped-packages.test.js
  test/simple.js
  test/simple.test.js
  test/symlink.test.js
  test/unsafe-cache.test.js
  test/yield.test.js
  tsconfig.json
  yarn.lock
Labels: PR: reviewed-approved

#386 docs: add badges in README
  .cspell.json
  README.md
Labels: PR: reviewed-approved

#370 GitHub Workflows security hardening
  .github/workflows/test.yml
Labels: PR: unreviewed, PR: small

#327 chore: add cSpell commit hook
  package.json
Labels: PR: reviewed-approved, PR: small
