Repository webpack/enhanced-resolve, pull requests merged in 2024-07, with the labels that each got.

#427 Avoid creating a new array inside doResolve.
  lib/Resolver.js
Labels: PR: reviewed-approved, PR: small

#428 fix: handle invalid files in `imports` and `exports` field properly
  .github/workflows/test.yml
  lib/ExportsFieldPlugin.js
  lib/ImportsFieldPlugin.js
  lib/util/entrypoints.js
  lib/util/path.js
  package.json
  test/exportsField.test.js
  test/fixtures/exports-field-invalid-package-target/a.js
  test/fixtures/exports-field-invalid-package-target/package.json
  test/fixtures/imports-field-different/a.js
  test/fixtures/imports-field-different/package.json
  test/importsField.test.js
  test/path.test.js
Labels: PR: unreviewed

#429 fix: `exports` and `imports` array target resolving
  lib/ExportsFieldPlugin.js
  lib/ImportsFieldPlugin.js
  lib/forEachBail.js
  test/__snapshots__/exportsField.test.js.snap
  test/__snapshots__/importsField.test.js.snap
  test/exportsField.test.js
  test/fixtures/exports-field-invalid-package-target/package.json
  test/fixtures/exports-field/node_modules/exports-field/package.json
  test/fixtures/exports-field2/node_modules/exports-field/package.json
  test/fixtures/imports-field-different/package.json
  test/fixtures/imports-field/node_modules/a/package.json
  test/importsField.test.js
  types.d.ts
Labels: PR: unreviewed

#431 ci: use laster Node@22
  .github/workflows/test.yml
Labels: PR: unreviewed, PR: small
